  name: Delövning 1 - Minimal Pipeline
  
  on: workflow_dispatch
  
  jobs:
    print-info:
      runs-on: ubuntu-latest # vilken runner?
      steps:
        - name: Printing to console # namnge steget
          run: echo "Pipeline started" # vad som ska göras
          
        - name: Checking version
          run: python --version