name: Delövning 2 - Parallella och sekventiella jobb

on:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Listing files
        run: |
          echo "Listing files available"
          ls -R
      

  print-message:
    runs-on: ubuntu-latest
    needs: list-files
    steps:
      - name: Meddelande
        run: echo "Detta körs efter list-files"