name: Delövning 4 - Triggers

on:
  push:
    branches:
      - 'main'
      - 'workflow-test'

  pull_request:
    types: [opened, closed]
    branches:
      - 'main'

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo info        
        run: echo "Workflow triggat av ${GITHUB_EVENT_NAME}"

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: trigger-test
    steps:
      - name: Announce pr merge
        run: |
          echo "The PR was merged"